-- Bakkeregister og salteføre.
--
-- Treningsloggen fantes allerede i basen: training_sessions med føre, vær,
-- antall runs, gren, porter, minutter og RPE. Det som manglet var to ting en
-- trener faktisk spør om.
--
-- 1. «Hva slags bakke var dette?» venue var fritekst, så svaret måtte skrives
--    hver gang og kunne ikke summeres. Nå er bakken en rad med en kjent
--    vanskelighetsgrad, hentet fra OpenStreetMap.
-- 2. Salteføre manglet i føre-lista. Salting er en egen tilstand i alpint, og
--    ikke en variant av hardt.

create table if not exists public.slopes (
  id bigint generated by default as identity primary key,
  -- Anlegget står som tekst og ikke som en fremmednøkkel til venues: venues
  -- er rennarenaer, og det trenes i mange bakker som aldri arrangerer renn.
  resort text not null,
  name text not null,
  difficulty text,
  lat double precision,
  lng double precision,
  osm_way_id bigint,
  -- OSM deler ofte én nedfart i flere ways. Antallet sier hvor mange som ble
  -- slått sammen til denne raden, og er nyttig når noe ser rart ut.
  segments integer default 1,
  source text default 'openstreetmap' not null,
  updated_at timestamp with time zone default now() not null
);

alter table public.slopes add constraint slopes_resort_name_key unique (resort, name);
alter table public.slopes add constraint slopes_difficulty_check
  check (difficulty is null or difficulty = any (array['novice','easy','intermediate','advanced','expert','freeride']));

create index if not exists slopes_resort_idx on public.slopes using btree (resort, name);

-- Referansedata, som venues: alle innloggede kan lese, ingen kan skrive
-- gjennom API-et. Registeret vedlikeholdes av scripts/fetch-slopes.mjs.
alter table public.slopes enable row level security;

drop policy if exists "slopes read" on public.slopes;
create policy "slopes read" on public.slopes as permissive for select to authenticated
  using (true);

grant all on table public.slopes to anon, authenticated, service_role;
grant all on sequence public.slopes_id_seq to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Treningsøkta peker på bakken
-- ---------------------------------------------------------------------------
alter table public.training_sessions
  add column if not exists slope_id bigint references public.slopes(id) on delete set null;

create index if not exists training_slope_idx on public.training_sessions using btree (slope_id);

-- venue beholdes som fritekst for steder som ikke er i registeret: utlandet,
-- små bakker, eller en løype som ikke er kartlagt ennå.
comment on column public.training_sessions.venue is
  'Fritekst for sted som ikke finnes i slopes. Bruk slope_id når bakken er kjent.';

-- ---------------------------------------------------------------------------
-- Salteføre
-- ---------------------------------------------------------------------------
alter table public.training_sessions drop constraint if exists training_sessions_snow_check;
alter table public.training_sessions add constraint training_sessions_snow_check
  check (snow = any (array['ice','salted','hard','grippy','soft','slush','powder','artificial']));
